language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
branches:
  only:
    - master
    - development
    - staging
before_install:
  - openssl aes-256-cbc -K $encrypted_4bcc15171aaf_key -iv $encrypted_4bcc15171aaf_iv -in google-services.json.enc -out app/google-services.json -d
  - openssl aes-256-cbc -K $encrypted_4bcc15171aaf_key -iv $encrypted_4bcc15171aaf_iv -in keystore.jks.enc -out keystore.jks -d
script:
  - ./deploy.sh
env:
  global:
    - DEPLOYGATE_USER_NAME=mukopikmin
    - secure: "XWW4Do1oKZ2zflqhIThgjqnNlZZGTFdyxXJGGv6RXGWT9WF1aVUs1UW7t0hOtu+dVKCYXM51YbR6yO1Fiq95MI0OQZpnxILIrUg+I6Rx1fFC92to6+IsIVQouqj2/xS6s3FrFdZSdTAtiG47U22m9iQPd6lmtjUi5PwW35Rt5SU8scOV3ozcC12QqLDWO6qZsgPWbOEariV9mFR0PZ0B+iMDJ6G8oD+Qe9qeBnZLsTv8TYyDR5o6sFTu6rt+ZQ0+iaf+RhdaZBQQoQWZEu41PXH/bIcxodbDunDrApmpjOWmxEja+cfh+oak1L271/09QWuCxrXgQKsyTyltSLvTdseXloUYGLo9HX4x38e4AbDFeyuzQNog+DIYDPKoXlVkIpHq6BpVA0sV+Vav/ypnaL6nMoUb/klCmsIhmlqoH0hFxb3fI5IMXesSk8CctwYlvcfOmELYKIHNcU5jts7xTtXATbjj3zqcBfzTkGkp7YliMxLaL0udNvctGMCEVKF996nrrFdBbHpPljg6Oxkvbk7Gg3JnSCEetlszVNCZfgxqNDgwTbeYNBZvwWK52Ya0+mIUGmMn5sP4czngm2Jc5r687hCjUmiUvICJx2fg5ijm03bld/DGSiMEePaEZ+Szhe2tjswgYiA0m+KUm6dOvYGou+7j+h3FxjBZcunGAaU="