name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decode google-services.json
      run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
    - name: Generate licence page
      run: ./gradlew generateLicensePage
    - name: Build with Gradle
      run: ./gradlew assembleDevelopment
    - name: Build signed APK
      run: |
        jarsigner \
          -verbose \
          -storepass $KEYSTORE_ALIAS_PASSWORD \
          -keypass $KEYSTORE_PASSWORD \
          -sigalg SHA1withRSA \
          -digestalg SHA1 \
          -keystore keystore.jks \
          -signedjar app/development/release/app-development-release.apk \
          app/build/outputs/apk/development/release/app-development-release-unsigned.apk \
          $KEYSTORE_ALIAS
      env:
        KEYSTORE_ALIAS_PASSWORD: ${{secrets.KEYSTORE_ALIAS_PASSWORD}}
        KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
    - name: Release to DeployGate
      run: ./gradlew uploadDeployGateDevelopmentRelease
      env:
        DEPLOYGATE_APP_OWNER_NAME: ${{secrets.DEPLOYGATE_APP_OWNER_NAME}}
        DEPLOYGATE_API_TOKEN: ${{secrets.DEPLOYGATE_API_TOKEN}}
      